name: Open AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run code reviewer
        id: run_code_reviewer
        run: |
          git fetch origin main
          git fetch origin ${{ github.event.pull_request.head.sha }}
          DIFF_TEXT=$(git diff origin/main ${{ github.event.pull_request.head.sha }})
          OUTPUT=$(node scripts/code-reviewer.mjs "$DIFF_TEXT")
          echo "review_response<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ${{ steps.run_code_reviewer.outputs.review_response }}